#!/usr/bin/env bash
# Sloučí kořenové markdown soubory do all_in_one.md. Volitelný argument = tag / ref.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"

source_ref="${1:-unspecified}"
out="${root}/all_in_one.md"
preferred=(README.md provoz.md zapojeni.md solar.md CHANGELOG.md)

{
  printf '%s\n' "<!-- Generated by scripts/build-all-in-one.sh. Do not edit. Source: ${source_ref} -->"
  printf '\n'
  printf '%s\n' "# Vše v jednom souboru"
  printf '\n'
  printf '%s\n' "Automaticky sloučeno z markdown souborů v kořeni při tagu / ref \`${source_ref}\`."
  printf '\n'

  printed=()
  is_printed() {
    local needle="$1" item
    for item in "${printed[@]+"${printed[@]}"}"; do
      [[ "$item" == "$needle" ]] && return 0
    done
    return 1
  }

  emit() {
    local f="$1"
    [[ -f "$f" ]] || return 0
    [[ "$f" == "all_in_one.md" ]] && return 0
    is_printed "$f" && return 0
    printed+=("$f")
    printf '\n---\n\n'
    printf '%s\n\n' "<!-- source: ${f} -->"
    cat "$f"
    printf '\n'
  }

  for f in "${preferred[@]}"; do
    emit "$f"
  done

  shopt -s nullglob
  for f in *.md; do
    emit "$f"
  done
} >"$out"
